// <auto-generated />
using System;
using MIU.Movimentations.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MIU.Movimentations.Infra.Migrations
{
    [DbContext(typeof(MovimentationContext))]
    [Migration("20210609140000_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MIU.Movimentations.Domain.Entities.Movimentation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)");

                    b.Property<DateTime>("MovimentationDate")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("MovimentationGain")
                        .HasColumnType("DECIMAL");

                    b.Property<decimal>("MovimentationLoss")
                        .HasColumnType("DECIMAL");

                    b.Property<int>("TributeAliquot")
                        .HasColumnType("INT");

                    b.Property<string>("TributeCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1000)");

                    b.Property<string>("TributeDescription")
                        .HasColumnType("VARCHAR(1000)");

                    b.HasKey("Id");

                    b.ToTable("Movimentation");
                });

            modelBuilder.Entity("MIU.Movimentations.Domain.Entities.Movimentation", b =>
                {
                    b.OwnsOne("MIU.Core.ValueObjects.CPF", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("MovimentationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("VARCHAR(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("MovimentationId");

                            b1.ToTable("Movimentation");

                            b1.WithOwner()
                                .HasForeignKey("MovimentationId");
                        });

                    b.Navigation("Cpf");
                });
#pragma warning restore 612, 618
        }
    }
}
